name: control
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.4.1
  - torchvision=0.19.1
  - pip:
      - albumentations==1.3.0
      - opencv-contrib-python==4.8.1.78
      - opencv-python==4.8.1.78
      - opencv-python-headless==4.8.1.78
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - pytorch-lightning>=2.0
      - omegaconf==2.1.1
      - test-tube>=0.7.5
      - einops==0.3.0
      - transformers==4.46.3
      - webdataset==0.2.5
      - kornia>=0.7
      - open_clip_torch
      - invisible-watermark>=0.1.5
      - torchmetrics
      - timm==1.0.26
      - addict==2.4.0
      - yapf==0.32.0
      - prettytable==3.6.0
      - safetensors
      - ipywidgets
      - hf_xet
      - gdown
      - xformers==0.0.27.post2
      - huggingface-hub[cli]
      - numpy==1.26.4
